version: "3"
services:
  server:
    image: elyspio/command-runner:arm64
    ports:
      - "4003:4000"
    environment:
      LOG_FOLDER: /var/logs
      SSH_USER: docker_admin
    volumes:
      - /apps/command-runner/logs:/var/logs
      - /apps/command-runner/.ssh/:~/.ssh
    restart: always
    container_name: command-runner
